[package]
name = "aoc"
version = "0.1.0"
authors = ["Rafael Serrano"]
edition = "2021"
default-run = "aoc"

[lib]
proc-macro = true

[profile.dev]
overflow-checks = false


[dependencies]
itertools = "0.10"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
regex = "1.10.2"
